// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.29/esri/copyright.txt for details.
//>>built
require({cache:{"esri/support/actions/actionUtils":function(){define(["exports","../../intl","../../intl/substitute"],function(f,d,h){f.getActionIcon=function(t){if(t.icon)return t.icon;if(!("image"in t&&t.image||t.className))return"question"};f.getActionStyles=function(t){return t?{backgroundImage:`url(${t})`}:{}};f.substituteActionImage=function({action:t,feature:y}){y=y?.attributes;return(t="image"in t?t.image:void 0)&&y?h.substitute(t,y):t??""};Object.defineProperty(f,Symbol.toStringTag,{value:"Module"})})},
"esri/widgets/LayerList/css":function(){define(["exports","../support/legacyIcon"],function(f,d){f.css={base:"esri-layer-list",widgetIcon:d.legacyIcon.layers,filterNoResults:"esri-layer-list__filter-no-results",item:"esri-layer-list__item",itemActive:"esri-layer-list__item--active",itemContent:"esri-layer-list__item-content",itemContentBottom:"esri-layer-list__item-content-bottom",itemMessage:"esri-layer-list__item-message",itemInvisibleAtScale:"esri-layer-list__item--invisible-at-scale",itemActionIcon:"esri-layer-list__item-action-icon",
itemActionImage:"esri-layer-list__item-action-image",itemTemporaryIcon:"esri-layer-list__item-temporary-icon",statusIndicator:"esri-layer-list__status-indicator",publishing:"esri-layer-list__publishing",updating:"esri-layer-list__updating",connectionStatus:"esri-layer-list__connection-status",connectionStatusConnected:"esri-layer-list__connection-status--connected",visibleToggle:"esri-layer-list__visible-toggle",visibleIcon:"esri-layer-list__visible-icon"};Object.defineProperty(f,Symbol.toStringTag,
{value:"Module"})})},"esri/widgets/LayerList/LayerListViewModel":function(){define("../../chunks/tslib.es6 ../../core/Collection ../../core/Evented ../../core/reactiveUtils ../../core/accessorSupport/decorators/property ../../core/has ../../core/Logger ../../core/RandomLCG ../../core/accessorSupport/decorators/subclass ./ListItem ./support/layerListUtils".split(" "),function(f,d,h,t,y,w,m,H,K,L,c){const u=d.ofType(L);d=class extends h.EventedAccessor{constructor(e){super(e);this.checkPublishStatusEnabled=
!1;this.listItemCreatedFunction=null;this.operationalItems=new u;this.view=null}initialize(){this.addHandles([t.watch(()=>!0===this.view?.ready,()=>this._viewHandles(),t.initial),t.watch(()=>[this.listItemCreatedFunction,this.checkPublishStatusEnabled],()=>this._recompileList())],"view")}destroy(){this.view=null;this.operationalItems.removeAll()}get state(){const {view:e}=this;return e?.ready?"ready":e?"loading":"disabled"}get totalItems(){return this.operationalItems.flatten(e=>e.children).length}triggerAction(e,
q){e&&!e.disabled&&this.emit("trigger-action",{action:e,item:q})}moveListItem(e,q,g,n){const p=e?.layer;if(p&&"subtype-sublayer"!==p.type){var E=this.view?.map?.layers,I=q?c.getItemLayers(q):E;E=g?c.getItemLayers(g):E;if(I&&E){var {operationalItems:k}=this,x=g?.children||k;n=E.length-n;e.parent=g||null;(q?.children||k).remove(e);I.remove(p);x.includes(e)||x.add(e,n);E.includes(p)||E.add(p,n);this._compileList()}}}_createLayerViewHandles(e){this.removeHandles("layer-views");this._compileList();e&&
this.addHandles(e.on("change",()=>this._compileList()),"layer-views")}_createMapLayerHandles(e){this.removeHandles("map-layers");this._compileList();e&&this.addHandles(e.on("change",()=>this._compileList()),"map-layers")}_createListItem(e){const {view:q,listItemCreatedFunction:g,checkPublishStatusEnabled:n}=this;return new L({checkPublishStatusEnabled:n,layer:e,listItemCreatedFunction:g,view:q})}_removeAllItems(){this.operationalItems.removeAll()}_getViewableLayers(e){if(e)return e.filter(q=>"hide"!==
c.findLayerListMode(q))}_watchLayersListMode(e){this.removeHandles("layer-list-mode");e&&e.forEach(q=>{"listMode"in q&&this.addHandles(t.watch(()=>q.listMode,()=>this._compileList()),"layer-list-mode")})}_compileList(){var e=this.view?.map?.layers;this._watchLayersListMode(e);e=this._getViewableLayers(e);e?.length?(this._createNewItems(e),this._removeItems(e),this._sortItems(e)):this._removeAllItems()}_createNewItems(e){const {operationalItems:q}=this;e.forEach(g=>{q.some(n=>n.layer===g)||q.add(this._createListItem(g))})}_removeItems(e){const {operationalItems:q}=
this,g=[];q.forEach(n=>{n&&e&&e.includes(n.layer)||g.push(n)});q.removeMany(g)}_sortItems(e){const {operationalItems:q}=this;q.sort((g,n)=>{g=e.indexOf(g.layer);n=e.indexOf(n.layer);return g>n?-1:g<n?1:0})}_recompileList(){this._removeAllItems();this._compileList()}_viewHandles(){const {view:e}=this;this.removeHandles(["map-layers","layer-views","view-layers"]);e?.ready?this.addHandles([t.watch(()=>this.view?.map?.allLayers,q=>this._createMapLayerHandles(q),t.initial),t.watch(()=>this.view?.allLayerViews,
q=>this._createLayerViewHandles(q),t.initial)],"view-layers"):this._removeAllItems()}};f.__decorate([y.property()],d.prototype,"checkPublishStatusEnabled",void 0);f.__decorate([y.property()],d.prototype,"listItemCreatedFunction",void 0);f.__decorate([y.property({type:u})],d.prototype,"operationalItems",void 0);f.__decorate([y.property({readOnly:!0})],d.prototype,"state",null);f.__decorate([y.property()],d.prototype,"totalItems",null);f.__decorate([y.property()],d.prototype,"view",void 0);return d=
f.__decorate([K.subclass("esri.widgets.LayerList.LayerListViewModel")],d)})},"esri/widgets/LayerList/ListItem":function(){define("../../chunks/tslib.es6 ../../core/Accessor ../../core/arrayUtils ../../core/Collection ../../core/Identifiable ../../core/reactiveUtils ../../core/accessorSupport/decorators/property ../../core/accessorSupport/decorators/cast ../../core/has ../../core/accessorSupport/decorators/subclass ../../core/accessorSupport/get ../../support/actions/ActionBase ../../support/actions/ActionButton ../../support/actions/ActionSlider ../../support/actions/ActionToggle ./ListItemPanel ./support/layerListUtils".split(" "),
function(f,d,h,t,y,w,m,H,K,L,c,u,e,q,g,n,p){var E;K=t.ofType({key:"type",defaultKeyValue:"button",base:u,typeMap:{button:e,toggle:g,slider:q}});const I=t.ofType(K);d=E=class extends y.IdentifiableMixin(d){constructor(k){super(k);this.actionsSections=new I;this.checkPublishStatusEnabled=this.actionsOpen=!1;this.children=new (t.ofType(E));this.childrenSortable=!0;this.hidden=!1;this.listItemCreatedFunction=this.layerView=this.layer=null;this.open=!1;this.parent=this.panel=null;this.sortable=!0;this.view=
null}initialize(){this.addHandles([w.watch(()=>[this.layer,this.layer?.listMode],()=>this._watchLayerProperties(this.layer),w.initial),w.watch(()=>this.checkPublishStatusEnabled,k=>this._updateChildrenPublishing(k),w.initial),w.watch(()=>this.view,k=>this._updateChildrenView(k),w.initial),w.watch(()=>this.panel,k=>this._setListItemOnPanel(k),w.initial),w.watch(()=>[this.layer,this.view],()=>this._getLayerView(),w.initial)]);"function"===typeof this.listItemCreatedFunction&&this.listItemCreatedFunction.call(null,
{item:this})}destroy(){this.view=null}get connectionStatus(){const {layerView:k,publishing:x}=this;if(!x&&k&&"connectionStatus"in k)return k.connectionStatus}get error(){return this.layer?.loadError}get incompatible(){const {layerView:k}=this;return k&&"spatialReferenceSupported"in k?!k.spatialReferenceSupported:!1}castPanel(k){this.panel?.open&&!k.hasOwnProperty("open")&&(k.open=!0);return k?new n(k):null}get title(){const k=c.get(this,"layer.layer");return(!k||k&&c.get(this,"layer.layer.loaded"))&&
c.get(this,"layer.title")||c.get(this,"layer.attributes.title")||""}set title(k){this._override("title",k)}get publishing(){const {layer:k,checkPublishStatusEnabled:x}=this;return x&&k&&"publishingInfo"in k&&"publishing"===k.publishingInfo?.status}get updating(){const {layerView:k,connectionStatus:x,layer:F,publishing:v}=this;return v||x?!1:k?k.updating:"loading"===F?.loadStatus||!1}get visible(){return this.layer?.visible}set visible(k){const x=this.layer;x&&(x.visible=k)}get visibleAtCurrentScale(){return!p.isLayerOutsideScaleRange(this.layer,
this.view?.scale)}get visibilityMode(){return p.findLayerVisibilityMode(this.layer)}clone(){return new E({actionsSections:this.actionsSections.clone(),actionsOpen:this.actionsOpen,checkPublishStatusEnabled:this.checkPublishStatusEnabled,children:this.children.clone(),childrenSortable:this.childrenSortable,hidden:this.hidden,layer:this.layer,listItemCreatedFunction:this.listItemCreatedFunction,open:this.open,panel:this.panel,parent:this.parent,sortable:this.sortable,title:this.title,view:this.view,
visible:this.visible})}_setListItemOnPanel(k){k&&(k.listItem=this)}_updateChildrenPublishing(k){const x=this.children;x&&x.forEach(F=>F.checkPublishStatusEnabled=k)}_updateChildrenView(k){const x=this.children;x&&x.forEach(F=>F.view=k)}_addChildren(k){this.removeHandles("child-list-mode");this.children.removeAll();if(k){k.forEach(F=>{this.addHandles(w.watch(()=>F.listMode,()=>this._addChildren(k)),"child-list-mode")});var x=k.filter(F=>"hide"!==p.findLayerListMode(F));this.children.addMany(this._makeChildren(x))}}_watchSublayerChanges(k){k&&
this.addHandles(k.on("change",()=>{this._addChildren(k)}),"layer")}_initializeChildLayers(k){this._addChildren(k);this._watchSublayerChanges(k)}_makeChildren(k){return k.map(x=>p.canDisplayLayer(x)?new E({layer:x,checkPublishStatusEnabled:this.checkPublishStatusEnabled,listItemCreatedFunction:this.listItemCreatedFunction,parent:this,view:this.view}):null).filter(h.isSome).reverse()}_watchLayerProperties(k){this.removeHandles("layer");this.removeHandles("child-list-mode");if(k)if("hide-children"===
p.findLayerListMode(k))this.children.removeAll();else{var x=p.getNormalizedChildLayerProperty(k);x&&this.addHandles(w.watch(()=>k[x],F=>{k.hasOwnProperty(x)&&this._initializeChildLayers(F)},w.initial),"layer")}}async _getLayerView(){const {layer:k,view:x}=this;if(k&&x)try{const F="subtype-sublayer"===k.type?k.parent:k,v=F&&await x.whenLayerView(F);v?.layer===F&&this._set("layerView",v)}catch{}}};f.__decorate([m.property({type:I})],d.prototype,"actionsSections",void 0);f.__decorate([m.property()],
d.prototype,"actionsOpen",void 0);f.__decorate([m.property()],d.prototype,"checkPublishStatusEnabled",void 0);f.__decorate([m.property({type:t})],d.prototype,"children",void 0);f.__decorate([m.property()],d.prototype,"childrenSortable",void 0);f.__decorate([m.property({readOnly:!0})],d.prototype,"connectionStatus",null);f.__decorate([m.property({readOnly:!0})],d.prototype,"error",null);f.__decorate([m.property()],d.prototype,"hidden",void 0);f.__decorate([m.property({readOnly:!0})],d.prototype,"incompatible",
null);f.__decorate([m.property()],d.prototype,"layer",void 0);f.__decorate([m.property({readOnly:!0})],d.prototype,"layerView",void 0);f.__decorate([m.property()],d.prototype,"listItemCreatedFunction",void 0);f.__decorate([m.property()],d.prototype,"open",void 0);f.__decorate([m.property({type:n})],d.prototype,"panel",void 0);f.__decorate([H.cast("panel")],d.prototype,"castPanel",null);f.__decorate([m.property()],d.prototype,"parent",void 0);f.__decorate([m.property()],d.prototype,"sortable",void 0);
f.__decorate([m.property()],d.prototype,"title",null);f.__decorate([m.property({readOnly:!0})],d.prototype,"publishing",null);f.__decorate([m.property({readOnly:!0})],d.prototype,"updating",null);f.__decorate([m.property()],d.prototype,"view",void 0);f.__decorate([m.property()],d.prototype,"visible",null);f.__decorate([m.property({readOnly:!0})],d.prototype,"visibleAtCurrentScale",null);f.__decorate([m.property({readOnly:!0})],d.prototype,"visibilityMode",null);return d=E=f.__decorate([L.subclass("esri.widgets.LayerList.ListItem")],
d)})},"esri/support/actions/ActionSlider":function(){define("../../chunks/tslib.es6 ../../core/accessorSupport/decorators/property ../../core/has ../../core/Logger ../../core/RandomLCG ../../core/accessorSupport/decorators/subclass ./ActionBase".split(" "),function(f,d,h,t,y,w,m){var H;h=H=class extends m{constructor(K){super(K);this.displayValueEnabled=!1;this.max=1;this.min=0;this.step=.1;this.type="slider";this.value=null}clone(){return new H({active:this.active,className:this.className,disabled:this.disabled,
id:this.id,indicator:this.indicator,title:this.title,visible:this.visible,displayValueEnabled:this.displayValueEnabled,max:this.max,min:this.min,step:this.step,value:this.value})}};f.__decorate([d.property()],h.prototype,"displayValueEnabled",void 0);f.__decorate([d.property()],h.prototype,"max",void 0);f.__decorate([d.property()],h.prototype,"min",void 0);f.__decorate([d.property()],h.prototype,"step",void 0);f.__decorate([d.property()],h.prototype,"value",void 0);return h=H=f.__decorate([w.subclass("esri.support.Action.ActionSlider")],
h)})},"esri/widgets/LayerList/ListItemPanel":function(){define("require ../../chunks/tslib.es6 ../../core/Identifiable ../../core/maybe ../../core/reactiveUtils ../../core/accessorSupport/decorators/property ../../core/has ../../core/Logger ../../core/RandomLCG ../../core/accessorSupport/decorators/subclass ../Widget ./support/layerListUtils ../support/widget ../support/jsxFactory".split(" "),function(f,d,h,t,y,w,m,H,K,L,c,u,e,q){h=class extends h.IdentifiableMixin(c){constructor(g,n){super(g,n);
this.content=this._legend=null;this.flowEnabled=!1;this.listItem=this.image=null;this.open=!1;this.visible=!0}initialize(){this.addHandles(y.watch(()=>this.content,g=>this._createLegend(g),y.initial))}destroy(){this._legend=t.destroyMaybe(this._legend)}get className(){const {image:g}=this,n=this._getFirstWidget();return this._get("className")||(!g&&n?n.iconClass??"":"")}set className(g){this._override("className",g)}get disabled(){const {listItem:g,_legend:n,content:p}=this;return g?Array.isArray(p)&&
1<p.length?!1:n?!n.activeLayerInfos?.length||!g.visibleAtCurrentScale||!g.visible:!1:!0}set disabled(g){this._overrideIfSome("disabled",g)}get title(){return this._get("title")||(this._getFirstWidget()?.label??"")}set title(g){this._override("title",g)}render(){return q.tsx("div",{class:"esri-list-item-panel"},this._renderContents())}_renderContent(g){const {_legend:n,disabled:p}=this;return!g||p?null:"legend"===g&&n?q.tsx("div",{key:"legend-widget"},n.render()):"string"===typeof g?q.tsx("div",{innerHTML:g,
key:g}):e.isWidget(g)?q.tsx("div",{key:"content-widget"},g.render()):g instanceof HTMLElement?q.tsx("div",{afterCreate:this._attachToNode,bind:g,key:"content-element"}):null}_renderContents(){const {content:g}=this;return Array.isArray(g)?g.map(n=>this._renderContent(n)):this._renderContent(g)}_getLegendOptions(){const {listItem:g}=this;if(!g)return{};const {layer:n,view:p}=g;return n&&p&&"subtype-sublayer"!==n.type?{view:p,layerInfos:[u.getLegendLayerInfo(n)]}:{}}async _createLegend(g){if(this._hasLegend(g)&&
!this._legend){({default:g}=await new Promise((E,I)=>f(["../Legend"],k=>E(Object.freeze(Object.defineProperty({__proto__:null,default:k},Symbol.toStringTag,{value:"Module"}))),I)));var {listItem:n}=this,p=new g(this._getLegendOptions());this._legend=p;this.notifyChange("className");this.notifyChange("title");g=y.watch(()=>[n?.view,n?.layer,n?.layer?.source,n?.layer?.parent],()=>this._updateLegend(p),y.initial);this.addHandles(g,"legends");this.scheduleRender()}}_hasLegend(g){return"legend"===g?!0:
null!=g&&(Array.isArray(g)?g.includes("legend"):!1)}_attachToNode(g){g.appendChild(this)}_updateLegend(g){g.set(this._getLegendOptions());this.scheduleRender()}_getWidget(g){return"legend"===g?this._legend:e.isWidget(g)?g:null}_getFirstWidget(){const {content:g}=this;return Array.isArray(g)?g.map(n=>this._getWidget(n)).find(n=>n):this._getWidget(g)}};d.__decorate([w.property()],h.prototype,"_legend",void 0);d.__decorate([w.property()],h.prototype,"className",null);d.__decorate([w.property()],h.prototype,
"content",void 0);d.__decorate([w.property()],h.prototype,"disabled",null);d.__decorate([w.property()],h.prototype,"flowEnabled",void 0);d.__decorate([w.property()],h.prototype,"image",void 0);d.__decorate([w.property()],h.prototype,"listItem",void 0);d.__decorate([w.property()],h.prototype,"open",void 0);d.__decorate([w.property()],h.prototype,"title",null);d.__decorate([w.property()],h.prototype,"visible",void 0);return h=d.__decorate([L.subclass("esri.widgets.LayerList.ListItemPanel")],h)})},"esri/widgets/LayerList/support/layerListUtils":function(){define(["exports"],
function(f){function d(c){return c?c.listMode===L.hideChildren:!1}function h(c){if(c)return null!=c.listMode?c.listMode:void 0}function t(c){return null!=c&&"minScale"in c&&null!=c.minScale?c.minScale:void 0}function y(c){return null!=c&&"maxScale"in c&&null!=c.maxScale?c.maxScale:void 0}function w(c){if(!(!c||"type"in c&&"wmts"===c.type||d(c)))return"sublayers"in c?"sublayers":"layers"in c?"layers":void 0}function m(c,u){c?.sort((e,q)=>{e="uid"in e?u.indexOf(e.uid):-1;q="uid"in q?u.indexOf(q.uid):
-1;return e>q?-1:e<q?1:0})}function H(c){return null!=c&&"layer"in c&&null!=c.layer}function K(c){return c&&"capabilities"in c&&null!=c.capabilities&&"exportMap"in c.capabilities?c.capabilities.exportMap:void 0}const L={hide:"hide",hideChildren:"hide-children"};f.areChildrenHidden=d;f.canDisplayLayer=function(c){return h(c)!==L.hide};f.canSortSublayers=function(c){c=(c?.layer&&H(c.layer)?c.layer.layer:void 0)??c?.layer;if(!c)return!1;c=K(c);return(null!=c&&"supportsDynamicLayers"in c?c.supportsDynamicLayers:
void 0)??!0};f.findLayerListMode=h;f.findLayerMaxScale=y;f.findLayerMinScale=t;f.findLayerVisibilityMode=function(c){if(!c)return"inherited";var u=H(c)?c.layer:c;u=K(u);u=null!=u&&"supportsSublayerVisibility"in u?u.supportsSublayerVisibility:void 0;return null!=u?u?"independent":"inherited":"visibilityMode"in c&&null!=c.visibilityMode?c.visibilityMode:"independent"};f.getItem=function(c){return c?.["data-item"]};f.getItemLayers=function(c){return(c=c?.layer)&&"layers"in c?c.layers:null};f.getLayerType=
function(c){return c?.getAttribute("data-layer-type")};f.getLegendLayerInfo=function(c){var u=H(c)?c:null;const e=c?.parent;return(u=null!=e&&"type"in e&&"map-image"===e.type?u?.source:null)&&e?{layer:e,title:"",sublayerIds:[u.mapLayerId]}:{layer:c,title:""}};f.getNormalizedChildLayerProperty=w;f.getStatusIcon=function({connectionStatus:c,publishing:u}){return c?"connected"===c?"beacon":"offline":u?"square":"bullet-point"};f.getVisibilityIcon=function({exclusive:c,visible:u,visibilityAppearance:e}){e=
"checkbox"===e;return u?c?"circle-f":e?"check-square-f":"view-visible":c?"circle":e?"square":"view-hide"};f.isLayerOutsideScaleRange=function(c,u){if(!c||null==u||isNaN(u))return!1;var e=t(c);c=y(c);e=null!=e&&!isNaN(e)&&0<e&&u>e;u=null!=c&&!isNaN(c)&&0<c&&u<c;return e||u};f.isSublayer=H;f.listItemHasChildren=function({children:c,error:u,incompatible:e}){return!!c?.filter(q=>!q.hidden).length&&!u&&!e};f.minDragEnabledItems=2;f.minFilterItems=10;f.sortChildLayersToIds=function(c,u){if(c=c?.layer){var e=
w(c);if(e){if("layers"===e&&"layers"in c)var q=c.layers;else"sublayers"===e&&"sublayers"in c&&(q=c.sublayers);m(q,u)}}};f.sortLayersToIds=m;f.sortableRoot="root";Object.defineProperty(f,Symbol.toStringTag,{value:"Module"})})},"esri/widgets/LayerList/LayerListVisibleElements":function(){define("../../chunks/tslib.es6 ../../core/Accessor ../../core/accessorSupport/decorators/property ../../core/has ../../core/Logger ../../core/RandomLCG ../../core/accessorSupport/decorators/subclass".split(" "),function(f,
d,h,t,y,w,m){d=class extends d{constructor(){super(...arguments);this.filter=this.errors=this.collapseButton=this.closeButton=!1;this.flow=!0;this.heading=!1;this.statusIndicators=!0;this.temporaryLayerIndicators=!1}};f.__decorate([h.property({type:Boolean,nonNullable:!0})],d.prototype,"closeButton",void 0);f.__decorate([h.property({type:Boolean,nonNullable:!0})],d.prototype,"collapseButton",void 0);f.__decorate([h.property({type:Boolean,nonNullable:!0})],d.prototype,"errors",void 0);f.__decorate([h.property({type:Boolean,
nonNullable:!0})],d.prototype,"filter",void 0);f.__decorate([h.property({type:Boolean,nonNullable:!0})],d.prototype,"flow",void 0);f.__decorate([h.property({type:Boolean,nonNullable:!0})],d.prototype,"heading",void 0);f.__decorate([h.property({type:Boolean,nonNullable:!0})],d.prototype,"statusIndicators",void 0);f.__decorate([h.property({type:Boolean,nonNullable:!0})],d.prototype,"temporaryLayerIndicators",void 0);return d=f.__decorate([m.subclass("esri.widgets.LayerList.LayerListVisibleElements")],
d)})},"esri/widgets/support/globalCss":function(){define(["exports"],function(f){f.globalCss={anchor:"esri-widget__anchor",anchorDisabled:"esri-widget__anchor--disabled",button:"esri-button",buttonDisabled:"esri-button--disabled",buttonHalf:"esri-button--half",buttonSecondary:"esri-button--secondary",buttonSmall:"esri-button--small",buttonTertiary:"esri-button--tertiary",buttonThird:"esri-button--third",disabled:"esri-disabled",disabledElement:"esri-disabled-element",empty:"esri-widget__content--empty",
emptyIllustration:"esri-widget__content-illustration--empty",heading:"esri-widget__heading",hidden:"esri-hidden",input:"esri-input",interactive:"esri-interactive",loader:"esri-widget__loader",loaderAnimation:"esri-widget__loader-animation",loaderText:"esri-widget__loader-text",menu:"esri-menu",menuHeader:"esri-menu__header",menuItem:"esri-menu__list-item",menuItemActive:"esri-menu__list-item--active",menuItemFocus:"esri-menu__list-item--focus",menuList:"esri-menu__list",noBookmarksIcon:"esri-widget__no-bookmark-icon",
panel:"esri-widget--panel",panelHeightOnly:"esri-widget--panel-height-only",primaryTick:"primary-tick",primaryTickAmPm:"primary-tick__ampm",primaryTickLabel:"primary-tick__label",rotating:"esri-rotating",secondaryTick:"secondary-tick",select:"esri-select",table:"esri-widget__table",widget:"esri-widget",widgetButton:"esri-widget--button",widgetButtonActive:"esri-widget--button-active",widgetDisabled:"esri-widget--disabled"};Object.defineProperty(f,Symbol.toStringTag,{value:"Module"})})},"*noref":1}});
define("require ../chunks/tslib.es6 ../core/Collection ../core/deprecate ../core/Logger ../core/ReactiveMap ../core/accessorSupport/decorators/property ../core/has ../core/RandomLCG ../core/accessorSupport/decorators/subclass ../support/actions/actionUtils ./Widget ./LayerList/css ./LayerList/LayerListViewModel ./LayerList/LayerListVisibleElements ./LayerList/ListItem ./LayerList/support/layerListUtils ../chunks/componentsUtils ./support/globalCss ./support/widgetUtils ./support/decorators/messageBundle ./support/decorators/vmEvent ./support/jsxFactory".split(" "),
function(f,d,h,t,y,w,m,H,K,L,c,u,e,q,g,n,p,E,I,k,x,F,v){const P=h.ofType(n);h=class extends u{constructor(a,b){super(a,b);this._activeItem=null;this._tooltipReferenceMap=new w;this._focusPanelFlowItem=this._focusRootFlowItem=!1;this._selectedDragItemLayerUid=this._lastDragDetail=null;this.dragEnabled=this.collapsed=!1;this.filterText=this.filterPlaceholder="";this.headingLevel=2;this.icon=null;this.iconClass=e.css.widgetIcon;this.messagesCommon=this.messages=this.listItemCanReceiveFunction=this.listItemCanGiveFunction=
null;this.minDragEnabledItems=p.minDragEnabledItems;this.minFilterItems=p.minFilterItems;this.selectedItems=new P;this.selectionMode="none";this.viewModel=new q;this.visibilityAppearance="default";this.visibleElements=new g;this._canMove=({dragEl:l,fromEl:r,toEl:z},A)=>{A="pull"===A?this.listItemCanGiveFunction:this.listItemCanReceiveFunction;l=p.getItem(l);if(!l?.sortable)return!1;const B=p.getItem(r);var D=p.getLayerType(r);const G=p.getItem(z);var M=p.getLayerType(z);D=!!D&&!!M&&D===M;M={selected:l,
from:B,to:G};return r.group&&z.group&&"function"===typeof A?A.call(null,M):D&&"sublayer"!==l?.layer?.type&&"map-image"!==B?.layer?.type&&"map-image"!==G?.layer?.type};this._clearActiveItem=()=>{this._activeItem=null};this._setActiveItem=l=>{"default"===this.visibilityAppearance&&(l=Array.from(l.composedPath()).find(r=>r.classList?.contains(e.css.item)),this._activeItem=p.getItem(l))};this._onCalciteListOrderChange=l=>{const {_lastDragDetail:r}=this,{toEl:z,fromEl:A,dragEl:B,newIndex:D}=l;A&&z&&(r?.newIndex!==
D||r?.dragEl!==B||r?.toEl!==z||r?.fromEl!==A)&&(this._lastDragDetail=l,A===z?(l=Array.from(A.children).filter(G=>G?.matches("calcite-list-item")).map(G=>G.value),this._sortLayers(A,l)):this._moveLayerFromChildList({toEl:z,fromEl:A,dragEl:B,newIndex:D}))}}loadDependencies(){return E.loadCalciteComponents({action:()=>new Promise((a,b)=>f(["../chunks/calcite-action"],a,b)),"action-group":()=>new Promise((a,b)=>f(["../chunks/calcite-action-group"],a,b)),"action-menu":()=>new Promise((a,b)=>f(["../chunks/calcite-action-menu"],
a,b)),button:()=>new Promise((a,b)=>f(["../chunks/calcite-button"],a,b)),flow:()=>new Promise((a,b)=>f(["../chunks/calcite-flow"],a,b)),"flow-item":()=>new Promise((a,b)=>f(["../chunks/calcite-flow-item"],a,b)),icon:()=>new Promise((a,b)=>f(["../chunks/calcite-icon"],a,b)),list:()=>new Promise((a,b)=>f(["../chunks/calcite-list"],a,b)),"list-item":()=>new Promise((a,b)=>f(["../chunks/calcite-list-item"],a,b)),notice:()=>new Promise((a,b)=>f(["../chunks/calcite-notice"],a,b)),tooltip:()=>new Promise((a,
b)=>f(["../chunks/calcite-tooltip"],a,b))})}destroy(){this._tooltipReferenceMap.clear()}get _dragEnabled(){return this.viewModel.totalItems>=this.minDragEnabledItems&&this.dragEnabled}get _filterEnabled(){return this.viewModel.totalItems>=this.minFilterItems&&this.visibleElements.filter}get label(){return this.messages?.widgetLabel??""}set label(a){this._overrideIfSome("label",a)}get listItemCreatedFunction(){return this.viewModel.listItemCreatedFunction}set listItemCreatedFunction(a){this.viewModel.listItemCreatedFunction=
a}get multipleSelectionEnabled(){t.deprecatedProperty(y.getLogger(this),"multipleSelectionEnabled",{replacement:"selectionMode",version:"4.29",warnOnce:!0});return"multiple"===this.selectionMode}set multipleSelectionEnabled(a){t.deprecatedProperty(y.getLogger(this),"multipleSelectionEnabled",{replacement:"selectionMode",version:"4.29",warnOnce:!0});this.selectionMode=a?"multiple":this.selectionEnabled?"single":"none"}get operationalItems(){return this.viewModel.operationalItems}set operationalItems(a){this.viewModel.operationalItems=
a}get selectionEnabled(){t.deprecatedProperty(y.getLogger(this),"selectionEnabled",{replacement:"selectionMode, dragEnabled",version:"4.29",warnOnce:!0});return"none"!==this.selectionMode&&this.dragEnabled}set selectionEnabled(a){t.deprecatedProperty(y.getLogger(this),"selectionEnabled",{replacement:"selectionMode, dragEnabled",version:"4.29",warnOnce:!0});this.selectionMode=(this.dragEnabled=a)?this.multipleSelectionEnabled?"multiple":"single":"none"}get view(){return this.viewModel.view}set view(a){this.viewModel.view=
a}triggerAction(a,b){return this.viewModel.triggerAction(a,b)}render(){var a=this.viewModel?.state;a={[I.globalCss.hidden]:"loading"===a,[I.globalCss.disabled]:"disabled"===a};const b=this.operationalItems?.filter(l=>!l.hidden&&(this.visibleElements.errors||!l.error));return v.tsx("div",{class:this.classes(e.css.base,I.globalCss.widget,I.globalCss.panel,a)},b?.length?[this._renderItemTooltips(b),this._renderItems(b)]:this._renderNoItems())}_renderItemTooltip(a){const {_tooltipReferenceMap:b,messages:l}=
this;return a?v.tsx("calcite-tooltip",{key:`tooltip-${a.layer.uid}`,referenceElement:b.get(a.layer.uid)},l.layerIncompatibleTooltip):null}_renderItemTooltipNodes(a){return a.incompatible?this._renderItemTooltip(a):a.children?.filter(b=>!b.hidden).toArray().map(b=>this._renderItemTooltipNodes(b))}_renderItemTooltips(a){return a?.toArray().map(b=>this._renderItemTooltipNodes(b))}_renderNoItemsMessage(){return v.tsx("div",{slot:"message"},this.messages.noItemsToDisplay)}_renderNoItems(){return v.tsx("div",
{class:e.css.itemMessage,key:"esri-layer-list__no-items"},v.tsx("calcite-notice",{icon:"information",kind:"info",open:!0,scale:"m",width:"full"},this._renderNoItemsMessage()))}_renderPanelFlowItems(a){return a?a.flatten(b=>b.children).filter(b=>!b.hidden).toArray().filter(({panel:b})=>b?.open&&!b.disabled&&b.flowEnabled).map(({title:b,panel:l})=>{const r=()=>this._handlePanelFlowItemBack(l);return v.tsx("calcite-flow-item",{afterCreate:this._focusPanelFlowItemNode,afterUpdate:this._focusPanelFlowItemNode,
bind:this,description:b,heading:l.title,headingLevel:this.headingLevel,key:`flow-panel-${l.uid}`,onCalciteFlowItemBack:z=>{z.preventDefault();r()}},l.render(),v.tsx("calcite-button",{appearance:"transparent",onclick:r,slot:"footer-actions",width:"full"},this.messagesCommon.back))}):[]}_handlePanelFlowItemBack(a){a.open=!1;this._focusRootFlowItem=!0}_focusRootFlowItemNode(a){this._focusRootFlowItem&&(this._focusRootFlowItem=!1,requestAnimationFrame(()=>a?.setFocus()))}_focusPanelFlowItemNode(a){this._focusPanelFlowItem&&
(this._focusPanelFlowItem=!1,requestAnimationFrame(()=>a?.setFocus()))}_renderItems(a){const {visible:b,collapsed:l,_filterEnabled:r,visibleElements:{closeButton:z,collapseButton:A,heading:B,flow:D},_dragEnabled:G,selectionMode:M,filterText:N,filterPlaceholder:O,messages:J}=this;a=[v.tsx("calcite-flow-item",{afterCreate:this._focusRootFlowItemNode,afterUpdate:this._focusRootFlowItemNode,bind:this,closable:z,closed:!b,collapsed:l,collapsible:A,heading:B?J.widgetLabel:void 0,headingLevel:this.headingLevel,
key:"root-flow-item",onCalciteFlowItemClose:()=>this.visible=!1},v.tsx("calcite-list",{afterCreate:C=>{C.addEventListener("focusin",this._setActiveItem);C.addEventListener("focusout",this._clearActiveItem)},afterRemoved:C=>{C.removeEventListener("focusin",this._setActiveItem);C.removeEventListener("focusout",this._clearActiveItem)},canPull:C=>this._canMove(C,"pull"),canPut:C=>this._canMove(C,"put"),"data-layer-type":"operational",dragEnabled:G,filterEnabled:r,filterPlaceholder:O,filterText:r?N:"",
group:p.sortableRoot,key:"root-list",label:J.widgetLabel,onmouseleave:this._clearActiveItem,onmouseover:this._setActiveItem,selectionAppearance:"border",selectionMode:M,onCalciteListChange:C=>this._handleCalciteListChange(C),onCalciteListDragEnd:C=>this._handleCalciteListDragEnd(C.detail),onCalciteListFilter:C=>this.filterText=C.target?.filterText??"",onCalciteListOrderChange:C=>this._onCalciteListOrderChange(C.detail)},a?.toArray().map(C=>this._renderItem(C)),a?.length&&r?v.tsx("div",{class:e.css.filterNoResults,
slot:"filter-no-results"},v.tsx("calcite-notice",{kind:"info",open:!0,scale:"m",width:"full"},this._renderNoItemsMessage())):null)),this._renderPanelFlowItems(a)];return b?D?v.tsx("calcite-flow",{key:"root-flow"},a):a:null}_renderChildList(a,b=[]){const {_dragEnabled:l}=this,{children:r}=a,z=p.listItemHasChildren(a),A=!p.areChildrenHidden(a.layer)&&!z&&l&&"group"===a.layer?.type;return z||A?v.tsx("calcite-list",{canPull:B=>this._canMove(B,"pull"),canPut:B=>this._canMove(B,"put"),"data-item":a,"data-layer-type":"operational",
dragEnabled:l?a.childrenSortable&&p.canSortSublayers(a):!1,group:a.layer.uid},r?.filter(B=>!B.hidden).toArray().map(B=>this._renderItem(B,a,[...b,a.title]))):null}_renderItemMessage(a){return a.error?v.tsx("div",{class:e.css.itemMessage,key:"esri-layer-list__error",slot:"content-bottom"},v.tsx("calcite-notice",{icon:"exclamation-mark-triangle",kind:"warning",open:!0,scale:"s",width:"full"},v.tsx("div",{slot:"message"},this.messages.layerError))):a.incompatible?v.tsx("div",{class:e.css.itemMessage,
key:"esri-layer-list__incompatible",slot:"content-bottom"},v.tsx("calcite-notice",{afterCreate:b=>this._setTooltipReference(b,a),afterRemoved:()=>this._removeTooltipReference(a),bind:this,icon:"exclamation-mark-triangle",kind:"warning",open:!0,scale:"s",tabIndex:0,width:"full"},v.tsx("div",{slot:"message"},this.messages.layerIncompatible))):null}_renderItem(a,b,l){const {_activeItem:r,_selectedDragItemLayerUid:z,selectionMode:A,selectedItems:B,messages:D}=this,G=a.title||D.untitledLayer,M=a.visibleAtCurrentScale?
G:`${G} (${D.layerInvisibleAtScale})`,N=this._filterActions(a.actionsSections),O=this._countActions(N);return v.tsx("calcite-list-item",{afterCreate:J=>this._focusSelectedDragEl(J,a),afterUpdate:J=>this._focusSelectedDragEl(J,a),class:this.classes(e.css.item,{[e.css.itemActive]:r===a}),"data-item":a,dragDisabled:!a.sortable,dragSelected:a.layer.uid===z,id:a.layer.uid,key:`list-item-${a.layer.uid}`,label:G,metadata:{parentTitles:l,title:G},open:a.open,selected:"none"!==A?B.includes(a):!1,title:M,value:a.layer.uid,
onCalciteListItemDragHandleChange:J=>this._handleCalciteListItemDragHandleChange(J,a),onCalciteListItemSelect:J=>this._handleCalciteListItemSelect(J,a,b),onCalciteListItemToggle:J=>this._handleCalciteListItemToggle(J,a)},v.tsx("div",{class:this.classes({[e.css.itemContent]:!0,[e.css.itemInvisibleAtScale]:!a.visibleAtCurrentScale}),slot:"content"},G),this._renderItemStatus(a,b),this._renderItemToggle(a,b),this._renderItemTemporaryIcon(a),this._renderChildList(a,l),this._renderItemMessage(a),this._renderPanel(a.panel),
this._renderPanelAction(a.panel),1<O?this._renderActionsSections(a,N):1===O?this._renderAction({item:a,action:this._getSingleActionButton(N),textEnabled:!1}):null)}_renderItemStatus(a,b){const {visibleElements:l}=this;if(!l.statusIndicators)return null;const {connectionStatus:r,publishing:z,updating:A}=a;a=!!r;return v.tsx("calcite-icon",{class:this.classes({[e.css.statusIndicator]:!0,[e.css.publishing]:z,[e.css.updating]:A&&!b,[e.css.connectionStatus]:a,[e.css.connectionStatusConnected]:a&&"connected"===
r}),icon:p.getStatusIcon({connectionStatus:r,publishing:z}),key:"layer-item-status",scale:"s",slot:"actions-end"})}_renderItemTemporaryIcon(a){return this.visibleElements.temporaryLayerIndicators&&"persistenceEnabled"in a.layer&&!a.layer.persistenceEnabled?v.tsx("calcite-icon",{class:e.css.itemTemporaryIcon,icon:"temporary",key:"temporary-icon",scale:"s",slot:"actions-start",title:this.messages.temporary}):null}_renderItemToggle(a,b){const {messages:l,visibilityAppearance:r}=this,{visible:z}=a,A=
b?.visibilityMode;if("inherited"===A)return null;const B=p.getVisibilityIcon({visible:z,exclusive:"exclusive"===A,visibilityAppearance:r}),D="checkbox"===r;return v.tsx("calcite-action",{appearance:"transparent",class:e.css.visibleToggle,icon:D?B:void 0,key:"visibility-toggle",onclick:()=>this._toggleVisibility(a,b),scale:"s",slot:D?"actions-start":"actions-end",text:l.layerVisibility,title:l.layerVisibility},D?null:v.tsx("calcite-icon",{class:this.classes({[e.css.visibleIcon]:"exclusive"!==A&&z}),
icon:B,scale:"s"}))}_renderPanel(a){return!a?.open||a.disabled||a.flowEnabled?null:v.tsx("div",{class:e.css.itemContentBottom,key:`content-panel-${a.uid}`,slot:"content-bottom"},a.render())}_renderPanelAction(a){if(!a?.visible)return null;const {open:b,title:l,disabled:r}=a;return v.tsx("calcite-action",{active:b,appearance:"transparent",disabled:r,icon:c.getActionIcon(a),key:`action-${a.uid}`,onclick:()=>this._togglePanel(a),scale:"s",slot:"actions-end",text:l??"",title:l??void 0},this._renderFallbackIcon(a))}_renderActionsSections(a,
b){return v.tsx("calcite-action-menu",{appearance:"transparent",key:"item-action-menu",label:this.messagesCommon.menu,open:a.actionsOpen,overlayPositioning:"fixed",placement:"bottom-end",scale:"s",slot:"actions-end",onCalciteActionMenuOpen:l=>a.actionsOpen=l.target.open},v.tsx("calcite-action",{appearance:"transparent",icon:"ellipsis",scale:"s",slot:"trigger",text:this.messagesCommon.options,title:this.messagesCommon.options}),b.toArray().map((l,r)=>this._renderActionSection(a,l,r)))}_renderActionSection(a,
b,l){return v.tsx("calcite-action-group",{key:`action-section-${l}`},b.toArray().map(r=>this._renderAction({item:a,action:r,textEnabled:!0})))}_renderFallbackIcon(a){const {className:b,icon:l}=a;if(l)return null;a="image"in a?a.image:void 0;const r={[e.css.itemActionIcon]:!!b,[e.css.itemActionImage]:!!a};b&&(r[b]=!0);return a||b?v.tsx("span",{"aria-hidden":"true",class:this.classes(e.css.itemActionIcon,r),key:"icon",styles:c.getActionStyles(a)}):null}_renderAction(a){const {item:b,action:l,textEnabled:r}=
a,{active:z,disabled:A,title:B,type:D,indicator:G}=l;return v.tsx("calcite-action",{active:"toggle"===D?l.value:!1,appearance:"transparent",disabled:A,icon:c.getActionIcon(l),indicator:G,key:`action-${l.uid}`,loading:z,onclick:()=>this._triggerAction(b,l),scale:"s",slot:r?void 0:"actions-end",text:B??"",textEnabled:r,title:B??void 0},this._renderFallbackIcon(l))}_setTooltipReference(a,b){this._tooltipReferenceMap.set(b.layer.uid,a)}_removeTooltipReference(a){this._tooltipReferenceMap.delete(a.layer.uid)}_moveLayerFromChildList({toEl:a,
fromEl:b,dragEl:l,newIndex:r}){l=p.getItem(l);a=p.getItem(a);b=p.getItem(b);this.viewModel.moveListItem(l,b,a,r)}_handleCalciteListDragEnd(a){const {fromEl:b,dragEl:l,oldIndex:r}=a;b.insertBefore(l,b.children[r])}_sortLayers(a,b){a&&(a.group===p.sortableRoot?p.sortLayersToIds(this.view?.map?.layers,b):(a=p.getItem(a))&&p.sortChildLayersToIds(a,b))}_getSingleActionButton(a){return a.reduce(b=>b).filter(b=>b&&"button"===b.type).at(0)}_filterActions(a){return a.map(b=>b.filter(l=>l.visible))}_countActions(a){return a.reduce((b,
l)=>b+l.length,0)}_triggerAction(a,b){b&&a&&("toggle"===b.type&&(b.value=!b.value),this.triggerAction(b,a))}_handleCalciteListChange(a){const {selectionMode:b,selectedItems:l}=this;"none"!==b&&(a=a.target.selectedItems.map(r=>p.getItem(r)).filter(Boolean),l.removeAll(),l.addMany(a))}_handleCalciteListItemToggle(a,b){a.stopPropagation();b.open=a.target.open}_focusSelectedDragEl(a,b){this._selectedDragItemLayerUid===b.layer.uid&&requestAnimationFrame(()=>a?.setFocus())}_handleCalciteListItemDragHandleChange(a,
b){a.stopPropagation();this._selectedDragItemLayerUid=a.target.dragSelected?b.layer.uid:null}_handleCalciteListItemSelect(a,b,l){p.getItem(a.target)===b&&"none"===this.selectionMode&&"inherited"!==l?.visibilityMode&&this._toggleVisibility(b,l)}_togglePanel(a){a.open=!a.open;a.open&&(this._focusPanelFlowItem=!0)}_toggleVisibility(a,b){!a||"exclusive"===b?.visibilityMode&&a.visible||(a.visible=!a.visible)}};d.__decorate([m.property()],h.prototype,"_activeItem",void 0);d.__decorate([m.property()],h.prototype,
"_tooltipReferenceMap",void 0);d.__decorate([m.property()],h.prototype,"_focusRootFlowItem",void 0);d.__decorate([m.property()],h.prototype,"_focusPanelFlowItem",void 0);d.__decorate([m.property()],h.prototype,"_dragEnabled",null);d.__decorate([m.property()],h.prototype,"_filterEnabled",null);d.__decorate([m.property()],h.prototype,"collapsed",void 0);d.__decorate([m.property()],h.prototype,"dragEnabled",void 0);d.__decorate([m.property()],h.prototype,"filterPlaceholder",void 0);d.__decorate([m.property()],
h.prototype,"filterText",void 0);d.__decorate([m.property()],h.prototype,"headingLevel",void 0);d.__decorate([m.property()],h.prototype,"icon",void 0);d.__decorate([m.property()],h.prototype,"iconClass",void 0);d.__decorate([m.property()],h.prototype,"label",null);d.__decorate([m.property()],h.prototype,"listItemCanGiveFunction",void 0);d.__decorate([m.property()],h.prototype,"listItemCanReceiveFunction",void 0);d.__decorate([m.property()],h.prototype,"listItemCreatedFunction",null);d.__decorate([m.property(),
x.messageBundle("esri/widgets/LayerList/t9n/LayerList")],h.prototype,"messages",void 0);d.__decorate([m.property(),x.messageBundle("esri/t9n/common")],h.prototype,"messagesCommon",void 0);d.__decorate([m.property()],h.prototype,"minDragEnabledItems",void 0);d.__decorate([m.property()],h.prototype,"minFilterItems",void 0);d.__decorate([m.property()],h.prototype,"multipleSelectionEnabled",null);d.__decorate([m.property()],h.prototype,"operationalItems",null);d.__decorate([m.property()],h.prototype,
"selectionEnabled",null);d.__decorate([m.property()],h.prototype,"selectedItems",void 0);d.__decorate([m.property()],h.prototype,"selectionMode",void 0);d.__decorate([m.property()],h.prototype,"view",null);d.__decorate([F.vmEvent("trigger-action"),m.property({type:q})],h.prototype,"viewModel",void 0);d.__decorate([m.property()],h.prototype,"visibilityAppearance",void 0);d.__decorate([m.property({type:g,nonNullable:!0})],h.prototype,"visibleElements",void 0);return h=d.__decorate([L.subclass("esri.widgets.LayerList")],
h)});